batch_size: 1
epochs: 20
eval_split: split/eval/panoptic_eccv.txt
checkpoint_path: 'logs/SURREAL/checkpoints/model_epoch_0030.pth'
experiment_name: Panoptic
hidden_num: 512
latent_dim: 512
logging_root: ./eval
lr: 0.0001
num_instances: 2160
point_cloud_path: datasets/Panoptic/vertex_pts_n_normal
vertex_path: datasets/Panoptic/vertex_pts_n_normal