batch_size: 1
epochs: 30
eval_split: split/eval/shrec19.txt
checkpoint_path: 'logs/SURREAL/checkpoints/model_epoch_0030.pth'
experiment_name: SHREC19
hidden_num: 512
latent_dim: 512
logging_root: ./eval
lr: 0.0001
num_instances: 2160
on_surface_points: 8000
point_cloud_path: datasets/SHREC19/surface_pts_n_normal
vertex_path: datasets/SHREC19/vertex_pts_n_normal
mesh_dir: /mnt/disk1/datasets/SHREC19/Al_ply