batch_size: 1
epochs: 30
eval_split: split/eval/shrec19.txt
checkpoint_path: 'logs/SURREAL/checkpoints/model_epoch_0030.pth'
experiment_name: SHREC19_Outlier
hidden_num: 512
latent_dim: 512
logging_root: ./eval
lr: 0.0001
num_instances: 2160
point_cloud_path: datasets/SHREC19_Outlier/vertex_pts_n_normal